# Generated by Django 5.1.4 on 2024-12-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_title', models.CharField(max_length=255, null=True)),
                ('carousel_one_title', models.CharField(max_length=100, null=True)),
                ('carousel_one_description', models.TextField(null=True)),
                ('carousel_one_image', models.ImageField(null=True, upload_to='img')),
                ('carousel_two_title', models.CharField(max_length=100, null=True)),
                ('carousel_two_description', models.TextField(null=True)),
                ('carousel_two_image', models.ImageField(null=True, upload_to='img')),
                ('carousel_three_title', models.CharField(max_length=100, null=True)),
                ('carousel_three_description', models.TextField(null=True)),
                ('carousel_three_image', models.ImageField(null=True, upload_to='img')),
                ('carousel_one_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_one_category', to='store.category')),
                ('carousel_three_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_three_category', to='store.category')),
                ('carousel_two_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_two_category', to='store.category')),
            ],
        ),
    ]
