# Generated by Django 5.1.4 on 2024-12-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_product_image_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_one_category',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_three_category',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_two_category',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_one_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_one_products', to='store.products'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_three_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_three_products', to='store.products'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_two_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_two_products', to='store.products'),
        ),
    ]
