# Generated by Django 5.1.4 on 2024-12-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_carousel_carousel_one_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('spclofferonetitle', models.CharField(max_length=255, null=True)),
                ('spclofferonecommission', models.CharField(max_length=20, null=True)),
                ('spclofferoneimage', models.ImageField(null=True, upload_to='img')),
                ('spcloffertwotitle', models.CharField(max_length=255, null=True)),
                ('spcloffertwocommission', models.CharField(max_length=20, null=True)),
                ('spcloffertwoimage', models.ImageField(null=True, upload_to='img')),
                ('spclofferoneproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spclofferone_products', to='store.products')),
                ('spcloffertwoproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spcloffertwo_products', to='store.products')),
            ],
        ),
    ]
