# Generated by Django 5.1.4 on 2024-12-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('actualprice', models.CharField(max_length=20, null=True)),
                ('discountedprice', models.CharField(max_length=20, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_image_products', to='store.products')),
            ],
        ),
    ]
