# Generated by Django 5.1.4 on 2024-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='actualprice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discountedprice',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
