# Generated by Django 5.1.4 on 2024-12-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_image', to='store.product_image'),
        ),
    ]
