# Generated by Django 5.1.4 on 2024-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actualprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discountedprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
