# Generated by Django 5.1.4 on 2024-12-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_wanjos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanjos',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.wanjos'),
        ),
    ]
