# Generated by Django 5.1.4 on 2024-12-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
