# Generated by Django 5.1.4 on 2024-12-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_cartitem_user_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
