# Generated by Django 5.1.4 on 2024-12-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='additionalinfo',
            field=models.TextField(null=True),
        ),
    ]
