# Generated by Django 5.1.4 on 2024-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_review_name_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_time_of_addition',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
