# Generated by Django 5.1.4 on 2024-12-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_cartitem_price_at_time_of_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_time_of_addition',
        ),
    ]
