# Generated by Django 5.1.4 on 2024-12-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
