# Generated by Django 4.2.17 on 2025-01-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actualprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discountedprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
