# Generated by Django 5.1.3 on 2025-01-13 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_products_actualprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('purchased', 'purchased')], max_length=20, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='store.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statususer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
