# Generated by Django 5.1.3 on 2025-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_purchasedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('purchased', 'purchased'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
