# Generated by Django 5.1.3 on 2025-01-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_orderhistory_customer_email_orderhistory_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('purchased', 'purchased')], default='purchased', max_length=50),
        ),
    ]
