# Generated by Django 5.1.3 on 2025-01-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_orderhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='verified',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='store.products'),
        ),
        migrations.DeleteModel(
            name='purchasedProducts',
        ),
    ]
