# Generated by Django 5.1.3 on 2025-01-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_remove_orderhistory_verified_orderhistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
