# Generated by Django 4.2.17 on 2025-01-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_herocontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='herocontent',
        ),
    ]
