# Generated by Django 4.2.17 on 2025-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_delete_herocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField(null=True)),
                ('page_image', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
