# Generated by Django 4.2.17 on 2025-01-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_alter_carousel_carousel_one_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'carousel', 'verbose_name_plural': 'Hero Content'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='featured_products',
            options={'verbose_name': 'featured_products', 'verbose_name_plural': 'Featured Products'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'OrderHistory', 'verbose_name_plural': 'Order Histories'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Pages', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='product_image',
            options={'verbose_name': 'Product_image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'verbose_name': 'ShippingDetails', 'verbose_name_plural': 'Shipping Details'},
        ),
        migrations.AlterModelOptions(
            name='special_offer',
            options={'verbose_name': 'special_offer', 'verbose_name_plural': 'Special Offer'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'subcategory', 'verbose_name_plural': 'Sub Category'},
        ),
        migrations.DeleteModel(
            name='productfeatures',
        ),
    ]
