# Generated by Django 4.2.17 on 2025-01-16 01:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_carousel_carousel_one_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='img'),
        ),
    ]
