# Generated by Django 4.2.17 on 2025-01-17 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_alter_pages_page_image_alter_shippingdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='img'),
        ),
    ]
