# Generated by Django 4.2.17 on 2025-01-17 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_remove_cart_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='img'),
        ),
    ]
