# Generated by Django 4.2.17 on 2025-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_footerpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpages',
            name='is_visible',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='footerpages',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
