# Generated by Django 4.2.17 on 2025-01-20 18:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_footerpages_is_visible_footerpages_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerpages',
            options={'verbose_name': 'footerpages', 'verbose_name_plural': 'FooterPages'},
        ),
        migrations.RemoveField(
            model_name='footerpages',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='footerpages',
            name='page',
        ),
        migrations.AddField(
            model_name='footerpages',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerpages',
            name='page_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='img'),
        ),
        migrations.AddField(
            model_name='footerpages',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footerpages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
