# Generated by Django 4.2.17 on 2025-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_alter_footerpages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpages',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
