# Generated by Django 4.2.17 on 2025-01-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_footerpages_is_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='footerpages',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
