# Generated by Django 4.2.17 on 2025-01-22 17:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_delete_footerpages_delete_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
